version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - /app/apps/backend/node_modules
    env_file:
      - apps/backend/.env
    environment:
      - NODE_ENV=development
    restart: always
    networks:
      - church      
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "512M"

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "8090:80"
    volumes:
      - /app/node_modules
      - /app/apps/frontend/node_modules
    env_file:
      - apps/frontend/.env
    restart: always
    depends_on:
      - backend
    networks:
      - church
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "128M"
          
networks:
  church:
    driver: bridge
  interactive-display-network:
    external: true