services:
  backend:
    container_name: backend
    image: tiagoluizpoli/church-backend:${DOCKER_BACKEND_TAG:-latest}
    pull_policy: always
    # build:
    #   context: .
    #   dockerfile: apps/backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - /app/apps/backend/node_modules
      - ./app/data:/app/data
    env_file:
      - apps/backend/.env   
    environment:
      - NODE_ENV=development
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "1G"

  frontend:
    container_name: frontend
    image: tiagoluizpoli/church-frontend:${DOCKER_FRONTEND_TAG:-latest}
    pull_policy: always
    ports:
      - "8090:80"
    volumes:
      - /app/node_modules
      - /app/apps/frontend/node_modules
    env_file:
      - apps/frontend/.env
    restart: always
    depends_on:
      - backend    
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "128M"
  